// <auto-generated />
namespace CyberSolar.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Product_categoryName_Removed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Product_categoryName_Removed));
        
        string IMigrationMetadata.Id
        {
            get { return "201912011405599_Product_categoryName_Removed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
